export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const EMPTY_INGREDIENT = 'EMPTY_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const BURGER_LOADING = 'BURGER_LOADING';
export const SAVE_AUTH = 'SAVE_AUTH';
export const LOG_OUT = 'LOG_OUT';